export type AiModel = {
  model: string;
  ragTopN: number;
  creditsPerMessage: number;
  baseURL?: string;
  supportsImages?: boolean;
  deprecated?: boolean;
  displayName?: string;
  provider?: string;
  speed?: string;
  accuracy?: string;
  addedAt?: Date;
};

export const oldModels: Record<string, AiModel> = {
  gpt_4o_mini: {
    model: "openai/gpt-4o-mini",
    ragTopN: 4,
    creditsPerMessage: 1,
    supportsImages: true,
    baseURL: "https://openrouter.ai/api/v1",
  },
  o3_mini: {
    model: "o3-mini",
    ragTopN: 2,
    creditsPerMessage: 1,
  },
  sonnet_3_7: {
    model: "claude-3-7-sonnet-20250219",
    ragTopN: 2,
    baseURL: "https://api.anthropic.com/v1",
    creditsPerMessage: 4,
  },
  sonnet_3_5: {
    model: "claude-3-5-sonnet-20241022",
    ragTopN: 2,
    baseURL: "https://api.anthropic.com/v1",
    creditsPerMessage: 4,
  },
  gemini_2_5_flash: {
    model: "google/gemini-2.5-flash",
    ragTopN: 6,
    creditsPerMessage: 1,
    baseURL: "https://openrouter.ai/api/v1",
  },
  gemini_2_5_flash_lite: {
    model: "gemini-2.5-flash-lite-preview-06-17",
    ragTopN: 4,
    creditsPerMessage: 1,
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai/",
  },
  gemini_3_flash: {
    model: "google/gemini-3-flash-preview",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
  },
  o4_mini: {
    model: "o4-mini",
    ragTopN: 4,
    creditsPerMessage: 2,
    supportsImages: true,
  },
  gpt_5_nano: {
    model: "openai/gpt-5-nano",
    ragTopN: 4,
    creditsPerMessage: 1,
    supportsImages: true,
    baseURL: "https://openrouter.ai/api/v1",
  },
  gpt_5_mini: {
    model: "openai/gpt-5-mini",
    ragTopN: 4,
    creditsPerMessage: 1,
    supportsImages: true,
    baseURL: "https://openrouter.ai/api/v1",
  },
  gpt_5: {
    model: "openai/gpt-5",
    ragTopN: 4,
    creditsPerMessage: 4,
    supportsImages: true,
    baseURL: "https://openrouter.ai/api/v1",
  },
  gpt_5_1: {
    model: "openai/gpt-5.1",
    ragTopN: 4,
    creditsPerMessage: 4,
    supportsImages: true,
    baseURL: "https://openrouter.ai/api/v1",
  },
  gpt_5_2: {
    model: "openai/gpt-5.2",
    ragTopN: 4,
    creditsPerMessage: 4,
    supportsImages: true,
    baseURL: "https://openrouter.ai/api/v1",
  },
  sonnet_4_5: {
    model: "anthropic/claude-sonnet-4.5",
    ragTopN: 2,
    creditsPerMessage: 6,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
  },
  haiku_4_5: {
    model: "anthropic/claude-haiku-4.5",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
  },
  kimi_2_5: {
    model: "moonshotai/kimi-k2.5",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
  },
  minimax_m_2_1: {
    model: "minimax/minimax-m2.1",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
  },
  glm_4_7: {
    model: "z-ai/glm-4.7",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
  },
  "openai/gpt-4o-mini": {
    model: "gpt-4o-mini",
    ragTopN: 4,
    creditsPerMessage: 1,
    supportsImages: true,
    baseURL: "https://api.openai.com/v1",
  },
};

export const models: Record<string, AiModel> = {
  "openrouter/anthropic/claude-sonnet-4.6": {
    model: "anthropic/claude-sonnet-4.6",
    ragTopN: 2,
    creditsPerMessage: 6,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "Sonnet 4.6",
    provider: "Anthropic",
    speed: "Fast",
    accuracy: "Best",
    addedAt: new Date("2026-02-18"),
  },
  "openrouter/moonshotai/kimi-k2.5": {
    model: "moonshotai/kimi-k2.5",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "Kimi K2.5",
    provider: "Moonshot AI",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-02-18"),
  },
  "openrouter/minimax/minimax-m2.1": {
    model: "minimax/minimax-m2.1",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    displayName: "Minimax M2.1",
    provider: "Minimax",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-02-18"),
  },
  "openrouter/minimax/minimax-m2.5": {
    model: "minimax/minimax-m2.5",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    displayName: "Minimax M2.5",
    provider: "Minimax",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-02-23"),
  },
  "openrouter/minimax/minimax-m2.7": {
    model: "minimax/minimax-m2.7",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    displayName: "Minimax M2.7",
    provider: "Minimax",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-03-27"),
  },
  "openrouter/z-ai/glm-4.7": {
    model: "z-ai/glm-4.7",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    displayName: "GLM 4.7",
    provider: "Z-AI",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-02-18"),
  },
  "openrouter/z-ai/glm-5": {
    model: "z-ai/glm-5",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    displayName: "GLM 5",
    provider: "Z-AI",
    speed: "Fast",
    accuracy: "Good",
    addedAt: new Date("2026-02-18"),
  },
  "openrouter/google/gemini-3-flash-preview": {
    model: "google/gemini-3-flash-preview",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "Gemini 3 Flash",
    provider: "Google",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-02-18"),
    deprecated: true,
  },
  "openrouter/openai/gpt-5.2": {
    model: "openai/gpt-5.2",
    ragTopN: 4,
    creditsPerMessage: 4,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "GPT 5.2",
    provider: "OpenAI",
    speed: "Slow",
    accuracy: "Best",
    addedAt: new Date("2026-02-18"),
  },
  "openrouter/openai/gpt-5-nano": {
    model: "openai/gpt-5-nano",
    ragTopN: 4,
    creditsPerMessage: 1,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "GPT 5 Nano",
    provider: "OpenAI",
    speed: "Fast",
    accuracy: "Good",
    addedAt: new Date("2026-01-18"),
  },
  "openrouter/openai/gpt-5-mini": {
    model: "openai/gpt-5-mini",
    ragTopN: 4,
    creditsPerMessage: 1,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "GPT 5 Mini",
    provider: "OpenAI",
    speed: "Medium",
    accuracy: "Good",
    addedAt: new Date("2026-01-18"),
  },
  "openrouter/openai/gpt-5": {
    model: "openai/gpt-5",
    ragTopN: 4,
    creditsPerMessage: 4,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "GPT 5",
    provider: "OpenAI",
    speed: "Slow",
    accuracy: "Best",
  },
  "openrouter/openai/gpt-5.1": {
    model: "openai/gpt-5.1",
    ragTopN: 4,
    creditsPerMessage: 4,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "GPT 5.1",
    provider: "OpenAI",
    speed: "Slow",
    accuracy: "Best",
  },
  "openrouter/openai/gpt-5.4-mini": {
    model: "openai/gpt-5.4-mini",
    ragTopN: 4,
    creditsPerMessage: 4,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "GPT 5.4 Mini",
    provider: "OpenAI",
    speed: "Fast",
    accuracy: "Good",
    addedAt: new Date("2026-03-27"),
    deprecated: true,
  },
  "openrouter/anthropic/claude-sonnet-4.5": {
    model: "anthropic/claude-sonnet-4.5",
    ragTopN: 2,
    creditsPerMessage: 6,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "Sonnet 4.5",
    provider: "Anthropic",
    speed: "Fast",
    accuracy: "Best",
  },
  "openrouter/anthropic/claude-haiku-4.5": {
    model: "anthropic/claude-haiku-4.5",
    ragTopN: 4,
    creditsPerMessage: 2,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "Haiku 4.5",
    provider: "Anthropic",
    speed: "Fast",
    accuracy: "Good",
  },
  "openrouter/openai/gpt-4o-mini": {
    model: "openai/gpt-4o-mini",
    ragTopN: 4,
    creditsPerMessage: 1,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: true,
    displayName: "4o-mini",
    provider: "OpenAI",
    speed: "Super fast",
    accuracy: "Basic",
  },
  "openrouter/xiaomi/mimo-v2-pro": {
    model: "xiaomi/mimo-v2-pro",
    ragTopN: 4,
    creditsPerMessage: 3,
    baseURL: "https://openrouter.ai/api/v1",
    supportsImages: false,
    displayName: "MiMo V2 Pro",
    provider: "Xiaomi",
    speed: "Fast",
    accuracy: "Very good",
    addedAt: new Date("2026-03-28"),
  },
};
